//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEFF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ASSEFFEntities : DbContext
    {
        public ASSEFFEntities()
            : base("name=ASSEFFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Alianza> Alianza { get; set; }
        public virtual DbSet<Fraternidad> Fraternidad { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Operacion> Operacion { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Evidencia> Evidencia { get; set; }
        public virtual DbSet<Rol_Operacion> Rol_Operacion { get; set; }
    
        public virtual int ADD_ALUMNO(string aCTION, Nullable<int> mATRICULA, string nOMBRE, string aPP_PAT, string aPP_MAT, string tELEFONO, Nullable<int> eSTADO, Nullable<System.DateTime> cUMPLEANIOS, byte[] fOTO, string eMAIL, string cARRERA, string sEMESTRE, string fRATERNIDAD)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var mATRICULAParameter = mATRICULA.HasValue ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPP_PATParameter = aPP_PAT != null ?
                new ObjectParameter("APP_PAT", aPP_PAT) :
                new ObjectParameter("APP_PAT", typeof(string));
    
            var aPP_MATParameter = aPP_MAT != null ?
                new ObjectParameter("APP_MAT", aPP_MAT) :
                new ObjectParameter("APP_MAT", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(int));
    
            var cUMPLEANIOSParameter = cUMPLEANIOS.HasValue ?
                new ObjectParameter("CUMPLEANIOS", cUMPLEANIOS) :
                new ObjectParameter("CUMPLEANIOS", typeof(System.DateTime));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var cARRERAParameter = cARRERA != null ?
                new ObjectParameter("CARRERA", cARRERA) :
                new ObjectParameter("CARRERA", typeof(string));
    
            var sEMESTREParameter = sEMESTRE != null ?
                new ObjectParameter("SEMESTRE", sEMESTRE) :
                new ObjectParameter("SEMESTRE", typeof(string));
    
            var fRATERNIDADParameter = fRATERNIDAD != null ?
                new ObjectParameter("FRATERNIDAD", fRATERNIDAD) :
                new ObjectParameter("FRATERNIDAD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_ALUMNO", aCTIONParameter, mATRICULAParameter, nOMBREParameter, aPP_PATParameter, aPP_MATParameter, tELEFONOParameter, eSTADOParameter, cUMPLEANIOSParameter, fOTOParameter, eMAILParameter, cARRERAParameter, sEMESTREParameter, fRATERNIDADParameter);
        }
    
        public virtual int ADD_FRATE(string aCTION, string iD_FRATE, string nOMBRE, string iD_ALIANZA, byte[] lOGO, Nullable<int> pUNTOS)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var iD_FRATEParameter = iD_FRATE != null ?
                new ObjectParameter("ID_FRATE", iD_FRATE) :
                new ObjectParameter("ID_FRATE", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iD_ALIANZAParameter = iD_ALIANZA != null ?
                new ObjectParameter("ID_ALIANZA", iD_ALIANZA) :
                new ObjectParameter("ID_ALIANZA", typeof(string));
    
            var lOGOParameter = lOGO != null ?
                new ObjectParameter("LOGO", lOGO) :
                new ObjectParameter("LOGO", typeof(byte[]));
    
            var pUNTOSParameter = pUNTOS.HasValue ?
                new ObjectParameter("PUNTOS", pUNTOS) :
                new ObjectParameter("PUNTOS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_FRATE", aCTIONParameter, iD_FRATEParameter, nOMBREParameter, iD_ALIANZAParameter, lOGOParameter, pUNTOSParameter);
        }
    }
}
